"""empty message

Revision ID: 19861b05bb75
Revises: 
Create Date: 2021-03-21 16:26:04.821851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19861b05bb75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('datainicio', sa.String(), nullable=True),
    sa.Column('datafim', sa.String(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_autor'), 'book', ['autor'], unique=False)
    op.create_index(op.f('ix_book_datafim'), 'book', ['datafim'], unique=False)
    op.create_index(op.f('ix_book_datainicio'), 'book', ['datainicio'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_datainicio'), table_name='book')
    op.drop_index(op.f('ix_book_datafim'), table_name='book')
    op.drop_index(op.f('ix_book_autor'), table_name='book')
    op.drop_table('book')
    op.drop_table('user')
    # ### end Alembic commands ###
