"""empty message

Revision ID: 57e86b6b8392
Revises: 04c25dd67165
Create Date: 2021-03-07 19:13:45.008807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e86b6b8392'
down_revision = '04c25dd67165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'books', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
