"""empty message

Revision ID: 593cd595545b
Revises: 
Create Date: 2021-03-24 09:33:55.889571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593cd595545b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('Book', sa.Integer(), nullable=True),
    sa.Column('User', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_estrela'), 'avaliacao', ['estrela'], unique=False)
    op.create_index(op.f('ix_avaliacao_nota'), 'avaliacao', ['nota'], unique=False)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('datainicio', sa.String(), nullable=True),
    sa.Column('datafim', sa.String(), nullable=True),
    sa.Column('User', sa.Integer(), nullable=True),
    sa.Column('Avaliacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Avaliacao'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_autor'), 'book', ['autor'], unique=False)
    op.create_index(op.f('ix_book_datafim'), 'book', ['datafim'], unique=False)
    op.create_index(op.f('ix_book_datainicio'), 'book', ['datainicio'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_datainicio'), table_name='book')
    op.drop_index(op.f('ix_book_datafim'), table_name='book')
    op.drop_index(op.f('ix_book_autor'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_avaliacao_nota'), table_name='avaliacao')
    op.drop_index(op.f('ix_avaliacao_estrela'), table_name='avaliacao')
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
