"""empty message

Revision ID: 7ab60467b40b
Revises: 57e86b6b8392
Create Date: 2021-03-14 18:16:16.286811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab60467b40b'
down_revision = '57e86b6b8392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.create_index(op.f('ix_books_autor'), 'books', ['autor'], unique=False)
    op.create_index(op.f('ix_books_datafim'), 'books', ['datafim'], unique=False)
    op.create_index(op.f('ix_books_datainicio'), 'books', ['datainicio'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'books', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_datainicio'), table_name='books')
    op.drop_index(op.f('ix_books_datafim'), table_name='books')
    op.drop_index(op.f('ix_books_autor'), table_name='books')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
